### ISSUE TITLE
v0.7

### ISSUE THREAD

**Issue by ivirshup** [theislab/anndata#171]
I'd like to have some organization around the upcoming release. I'd like to have a list of all planned and included changes for `v0.7` Please edit this for anything I forgot!

## New features

* DataFrames everywhere
* Views of views #62
* `obsp`, `varp` for pairwise measures #136 
* Allow sparse data and dataframes in `.obsm`, `.varm`, `.layers`, `.uns` #134
* Updated `h5ad` spec (with backwards compatable reading)
* Lazy views for faster subsetting
* Better test coverage

## Breaking changes

* Modifying sparse `.X` inplace via a view, even if value was set with dense
* Indexing into `AnnData` object will not reduce dimensionality of contained arrays
  * Fixes #74 #60 #145

## TODO:

- [x] Unbreak zarr implemntation (broken in #167)
- [x] Restructure views, to allow views of view (merge #164)
- [x] Standardize results of indexing into `AnnData` (merge #164) (always 2d) #145
- [x] Add in `obsp`, `varp` attributes (uncomment)
- [x] Fix dense as sparse reading for h5ad
- [ ] Appropriate warnings for changed behaviour
- [x] Make sure `scanpy` and others work with new behaviour
- [x] deprecate `rename_categories`

**Comment by flying-sheep** [comment]
Do we want “2d only” (the second breaking change) in something called 0.7?

I think to signal a breaking change and closeness to 1.0, we could name this version 0.90 or so!

(not 0.99, because then we’ll end up having 0.999, 0.9999, …)

**Comment by flying-sheep** [comment]
Another change we could think about: unifying .layers and .X

Maybe .X should just be a property returning the first layer? or the layer called `X`?

**Comment by ivirshup** [comment]
>Do we want “2d only” (the second breaking change) in something called 0.7?
>
>I think to signal a breaking change and closeness to 1.0, we could name this version 0.90 or so!

I would understand the change from `v0.6.x` to `v0.7` to involve breaking changes. I don't like the idea of going to `v0.90` since it breaks from semantic versioning. Also, who knows, we may want `v0.8`-`v0.20`. For example, I'd say the possibility of having `.X` be one of `.layers` sounds like a great `v0.8` target to me, since it would require us to allow layers to be backed, and that'll take some time.

I would have to know that this was a dramatic change that broke a lot of stuff before thinking any out of the ordinary versioning semantics were used. The change to always 2d doesn't break many tests here or for scanpy. Additionally `scvelo` mostly runs with it.

I do think we should do a `v0.6.22` release of AnnData and `v1.4.4` of scanpy, so there's a version with working `scipy`/ `statsmodels` dependencies without this change. This would also give us space to transition users to `{obs,var}_vector`, since that will return a 1d array now, and once "always 2d" is in effect.

**Comment by flying-sheep** [comment]
Well, if the fallout isn’t that bad, I agree, we can just call it 0.7

That being said, skipping from `0.6.x` to `0.90` is completely compatible with semantic versioning. Why do you think it wasn’t? (And instead of 0.8, the next version would just be called `0.91`)

**Comment by falexwolf** [comment]
@ivirshup: Agreed with everything! Terrific! Agreed in particular with `0.6.22` and `1.4.4` before moving to `1.5` and `0.7`. In `0.6.22`, where the flattening is still present, can you add a warning _future versions will not flatten `.X` anymore_ when it's called?

**Comment by ivirshup** [comment]
@flying-sheep, I suppose `v0.90` would be compatible with establishing the order of versions, but I think of "incrementing the version" to imply incrementing on a fixed scale. I think my reaction to seeing a version change from `v0.6.22` to `v0.7.0` would be "there are breaking changes in this release", while `v0.6.22` to `v0.90.0` would be "what does this mean? What happened to `v0.7-v0.89`"?

**Comment by ivirshup** [comment]
I've added that warning, what else has to be done before we can release `0.6.22`?

**Comment by falexwolf** [comment]
Nothing, I think. I'm happy to make the release if you don't want to do it. 🙂

**Comment by ivirshup** [comment]
Just realized there are probably a couple bugs to fix prior to that:

- [ ] https://github.com/theislab/scanpy/issues/728 - Just fixing backwards compat for `_get_obs_
- [ ] https://github.com/theislab/scanpy/issues/699 - This is probably on the scanpy side. Should `sc.pp.scale` make a copy if it's called on a view? It currently does not if called on dense data, but does on sparse data. I think it should always make a copy if its on a view.
- [ ] `obs_vector` probably shouldn't throw a warning telling you to use `obs_vector`  😜

**Comment by falexwolf** [comment]
Great that you're addressing these!

> I think it should always make a copy if its on a view.

Agreed!

**Comment by ivirshup** [comment]
I think we're good for `0.6.22`. Scanpy will need a pass to remove warnings being thrown for `v1.4.4` though. Would you mind making this release @falexwolf?

**Comment by falexwolf** [comment]
Made release `0.6.22` for the current state of master: https://github.com/theislab/anndata/commit/34e8616fd92b893bdd8e4b6d4036830270961d19/, https://github.com/theislab/anndata/releases, https://pypi.org/project/anndata/#history. 🙂

**Comment by flying-sheep** [comment]
It would be great if you could start publishing wheels too, it’s almost no additional work:

```bash
python3 setup.py sdist bdist_wheel
twine upload dist/anndata-0.7{.tar.gz,-py3-none-any.whl}
```

I always have to go back and retroactively make wheels.

**Comment by falexwolf** [comment]
Oh sorry, I thought we stopped publishing wheels 1.5 years after going from cython to numba. 😆Had you told me that we wanted to continue (what for, btw?, there is no compilation involved), I'd continued publishing wheels of Mac.

**Comment by flying-sheep** [comment]
There’s not that much of an advantage anymore but wheels are faster to install, as setup.py doesn’t need to be run on the target machines – the wheels will simply be unpacked.

**Comment by ivirshup** [comment]
Could the release process get documented, potentially with scripts or snippets? I'd like to be able to help out with that, but I'd like to know I was doing it right.

**Comment by flying-sheep** [comment]
It’s not more than this, but we can document it, yes:

```console
$ git tag x.y.z
$ python3 setup.py sdist bdist_wheel
$ twine upload scanpy-x.y.z-py3-none-any.whl scanpy-x.y.z.tar.gz
$ git push --tags
```

**Comment by ivirshup** [comment]
Just push a big update which cleans up the reading and writing code a lot, as well as improving performance. It does make some changes to the on disk structure, but you should be able to read older files. Added features mean you can now have data frames and sparse matrices stored in any of the `obsm`, `varm`, `layers` etc.

It would be great if people could try out current master and let me know if they find any bugs!

**Comment by flying-sheep** [comment]
OK, so should we get this out before the X-layers merge (#244) and the modes (#237) land?

**Comment by ivirshup** [comment]
Yes! I need to take another look at fixing https://github.com/theislab/scanpy/issues/832 before this can go though. I'm going to check if there's any chance this could get sorted upstream first.

**Comment by flying-sheep** [comment]
Hmm, we should deprecate `rename_categories`, as it’s no longer necessary with the new categorical storage. I’ll do this before releasing the rc.

**Comment by LuckyMD** [comment]
What is the alternative to `rename_categories`? I'm using it quite a lot. It works both on the categoricals for the `obs` or `var` column, but also on any `rank_genes_groups()` results that are generated, no?

**Comment by flying-sheep** [comment]
It’s useless since the categories are no longer stored in `.uns`, just do:

```py
adata.obs['foo'].cat.categories = new_categories
# or
adata.obs['foo'].cat.rename_categories(..., inplace=True)
```

**Comment by LuckyMD** [comment]
The nice thing about `rename_categories` as it is at the moment is that it renames the `.uns` and `.obs`/`.var` stuff in a single command.

**Comment by flying-sheep** [comment]
We just (pre-)released AnnData 0.7rc1 with it deprecated. We should move the code to scanpy as a documented utility I think.

**Comment by flying-sheep** [comment]
Alex reverted stuff on master because there’s no alternatives, so our path forwards is now:

1. Scanpy needs to grow `utils.rename_categories` (or so) and `update_anndata` (or so)
2. obsp/varp warning and rename_categories deprecations needs to be reinstated before 0.7
3. people should be encouraged at the right places to migrate to obsp/varp (using `update_anndata`) and `scanpy.utils.rename_categories`.

**Comment by falexwolf** [comment]
Could we try to have a discussion instead of you making absolute statements?

1. semi-agreed, because of unclarity of alternatives, see our Slack discussion
2. disagreed on obsp/varp, it gives the user a horrible experience, and there are no alternatives, I worked with these warnings for a week now and got _very_ annoyed, so I muted them
3. agreed

**Comment by flying-sheep** [comment]
Sorry for not outlining this clearly enough, I was busy celebrating christmas and my birthday!

The plan is and always was to 1. get a anndata prerelease out with most deprecations in place 2. get a scanpy prerelease out with the stuff that is supposed to be in scanpy, 3. release final versions of anndata and scanpy

**Comment by flying-sheep** [comment]
OK, seems like we got it. Now to all the exciting changes enabled by this!
