### ISSUE TITLE
Allowing `.X` to be None

### ISSUE THREAD

**Issue by ivirshup** [theislab/anndata#467]
Tracking issue for allowing `X` to be `None`.

When parts get ticked off they should be marked with the PR that fixed them.

# TODO:

All of these need tests, some of them may already work.

- [ ] Getter, setter, deleter
- [ ] Initializer (seems to work, needs testing)
- [ ] Views (basically just check that `.X = None` doesn't change other view behavior, `a[idx].X` doesn't do anything weird, and copying views still works)
- [ ] `_subset_inplace`
- [ ] Copying
- [ ] Backed mode
- [ ] Concatenation
- [ ] Transpose
- [ ] Methods which default to values from `X`, e.g. `obs_vector`, `to_df`.
- [ ] IO (seems to work, needs testing)
  - [ ] Main writers (`zarr`, `hdf5`)
  - [ ] Main readers
  - [ ] Specialized writers like `to_csvs`
- [ ] Raw (pretty similar set of things to be checked)
  - [ ] Initializer
  - [ ] Backed
  - [ ] Copies
  - [ ] Concatenation
  - [ ] IO

**Comment by flying-sheep** [comment]
@rcannood which of the above points have been adressed by your PR?

**Comment by rcannood** [comment]
To begin: 
* Getter, setter, deleter
* Initializer
* Transpose

There are also some basic checks for 'Views', but not everything mentioned above has been taken care of so it's still WIP.

**Comment by ivirshup** [comment]
I've fixed up many of these cases in #677.

I think `.X is None` is now in a fairly useable state, and think we're in an alright place to push the rest to the next release.

**Comment by ivirshup** [comment]
Adding a point to the checklist:

Gotta figure out what the shape of the object is when X is None. Currently we figure out the shape of an AnnData by checking the shapes of `X`, `obs`, and `var` and asserting everything else fits that. What we should probably start doing is resolving the shape from all elements, so an AnnData with just `obsm`/ `varm` can be created.

-----------

An interesting question is what happens if you only provide elements aligned to one axis. E.g. just `obsm` or `obs`. Is `n_vars` unknown or zero?

Is this allowed?

```python
adata = AnnData(obs=obs)
```

Then what is `n_vars`. Would this be allowed after?

```python
adata.varm["x"] = np.ones((20, 10))
```

**Comment by AlbertoFabbri93** [comment]
Is this todo list updated? Can we use anndata with `X` being `None` or is it better to wait for 0.13?

**Comment by flying-sheep** [comment]
It has been working quite well for a while, good point!
